- title: EDA
  description: Subject-level analysis pipeline for "*Emotionen im Griff*" EDA-data
  catalog: NCSR Tools
  source: ../cnsr/EDA.ipynb
  type: notebook

- title: ERN
  description: Participant-level analysis pipeline for calculating ERN in the SART task
  catalog: NCSR Tools
  source: ../cnsr/ERN.ipynb
  type: notebook

- title: FAA
  description: Participant-level analysis pipeline for calculating frontal alpha asymmetry in the *MusEEG* project
  catalog: NCSR Tools
  source: ../cnsr/FAA.ipynb
  type: notebook

- title: FTT
  description: Subject-level analysis pipeline for FTT-fNIRs-data
  catalog: NCSR Tools
  source: ../cnsr/FTT.ipynb
  type: notebook

- title: HRV
  description: Subject-level analysis pipeline for FTT-fNIRs-data
  catalog: NCSR Tools
  source: ../cnsr/HRV.ipynb
  type: notebook

- title: Resting state
  description: Subject-level analysis pipeline for Resting state
  catalog: NCSR Tools
  source: ../cnsr/RS.ipynb
  type: notebook
